USE Analise

DROP TABLE IF EXISTS Dim_Tempo

CREATE TABLE Dim_Tempo (
    Data_ID INT PRIMARY KEY,
    Data_Completa DATE,
    Ano INT,
    Mes INT,
    Dia INT,
    Trimestre INT,
    Semana INT,
    Dia_Semana NVARCHAR(20),
    Feriado BIT DEFAULT 0
);
GO

DROP TABLE IF EXISTS Dim_UF

CREATE TABLE Dim_UF (
    UF_ID INT PRIMARY KEY IDENTITY(1,1),
    SG_UF NVARCHAR(2),
    NM_UF NVARCHAR(50),
    Regiao NVARCHAR(20)
);
GO

DROP TABLE IF EXISTS Dim_Cargo

CREATE TABLE Dim_Cargo (
    Cargo_ID INT PRIMARY KEY IDENTITY(1,1),
    CD_CARGO INT,
    DS_CARGO NVARCHAR(50)
);
GO

DROP TABLE IF EXISTS Dim_Partido

CREATE TABLE Dim_Partido (
    Partido_ID INT PRIMARY KEY IDENTITY(1,1),
    NR_PARTIDO INT,
    SG_PARTIDO NVARCHAR(20),
    NM_PARTIDO NVARCHAR(100)
);
GO

DROP TABLE IF EXISTS Dim_Municipio

CREATE TABLE Dim_Municipio (
    Municipio_ID INT PRIMARY KEY IDENTITY(1,1),
    CD_MUNICIPIO INT,
    NM_MUNICIPIO NVARCHAR(100),
    UF_ID INT,

     CONSTRAINT FK_Municipio_UF FOREIGN KEY (UF_ID) REFERENCES Dim_UF(UF_ID)
);
GO

DROP TABLE IF EXISTS Dim_Candidato

CREATE TABLE Dim_Candidato (
    Candidato_ID INT PRIMARY KEY IDENTITY(1,1),
    SQ_CANDIDATO BIGINT,
    NM_URNA_CANDIDATO NVARCHAR(100),
    NM_CANDIDATO NVARCHAR(200),
    NR_CANDIDATO NVARCHAR(10),
    UF_ID INT,
    Cargo_ID INT,
    Partido_ID INT,
    DS_GENERO NVARCHAR(20),
    DS_COR_RACA NVARCHAR(50),
    DS_GRAU_INSTRUCAO NVARCHAR(100),
    DS_OCUPACAO NVARCHAR(200),
    DT_NASCIMENTO DATE,
    DS_SITUACAO_CANDIDATURA NVARCHAR(100),
    DS_SIT_TOT_TURNO NVARCHAR(100),
    
    CONSTRAINT FK_Candidato_UF FOREIGN KEY (UF_ID) REFERENCES Dim_UF(UF_ID),
    CONSTRAINT FK_Candidato_Cargo FOREIGN KEY (Cargo_ID) REFERENCES Dim_Cargo(Cargo_ID),
    CONSTRAINT FK_Candidato_Partido FOREIGN KEY (Partido_ID) REFERENCES Dim_Partido(Partido_ID)
);
GO

DROP TABLE IF EXISTS Dim_Fornecedor

CREATE TABLE Dim_Fornecedor (
    Fornecedor_ID INT PRIMARY KEY IDENTITY(1,1),
    NR_CPF_CNPJ_FORNECEDOR NVARCHAR(100),
    NM_FORNECEDOR NVARCHAR(300),
    DS_TIPO_FORNECEDOR NVARCHAR(50)
);
GO

DROP TABLE IF EXISTS Dim_Doador

CREATE TABLE Dim_Doador (
    Doador_ID INT PRIMARY KEY IDENTITY(1,1),
    NR_CPF_CNPJ_DOADOR NVARCHAR(100),  
    NM_DOADOR NVARCHAR(300),
    DS_TIPO_DOADOR NVARCHAR(50)
);
GO

DROP TABLE IF EXISTS Dim_Tipo_Despesa

CREATE TABLE Dim_Tipo_Despesa (
    Tipo_Despesa_ID INT PRIMARY KEY IDENTITY(1,1),
    DS_ORIGEM_DESPESA NVARCHAR(200),
    DS_NATUREZA_DESPESA NVARCHAR(100)
);
GO

DROP TABLE IF EXISTS Dim_Tipo_Despesa_Contratada 

CREATE TABLE Dim_Tipo_Despesa_Contratada (
    Tipo_Despesa_Contratada_ID INT PRIMARY KEY IDENTITY(1,1),
    DS_ORIGEM_DESPESA NVARCHAR(200),
    DS_TIPO_FORNECEDOR NVARCHAR(50)
);
GO

DROP TABLE IF EXISTS Dim_Tipo_Receita

CREATE TABLE Dim_Tipo_Receita (
    Tipo_Receita_ID INT PRIMARY KEY IDENTITY(1,1),
    DS_ORIGEM_RECEITA NVARCHAR(200),
    DS_FONTE_RECEITA NVARCHAR(100)
);
GO